name: CI

on:
  create:
    tags:
      - v*

jobs:
  publish:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Install stylechecker
      run: pip install flake8
    - name: Run stylecheck
      run: flake8 .
    - name: Run tests
      run: GITHUB_REPOSITORY="" nosetests --with-doctest .