name: Publish package

on:
  create:
    tags:
      - v*

jobs:
  dist:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Install wheel package
        run: pip install wheel
      - name: Build wheel
        run: python setup.py bdist_wheel
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v1
        with:
          name: wheel
          path: dist

  publish:
    needs: dist
    runs-on: ubuntu-18.04

    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Download wheel
        uses: actions/download-artifact@v1
        with:
          name: wheel
      - name: Install twine
        run: pip install twine
      - name: Upload to PyPI
        run: twine upload wheel/*.whl
